#!/bin/sh
# first compile the files
ruby Server/boilerplate/compile_files.rb
# then run the file watcher (which will start the server and watch for changes)
ruby Server/boilerplate/watch_for_file_changes.rb